<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7bef8f53-b20c-4465-9e46-81406bba8435}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Machine : MachineModule := (Name := 'Machine');
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Machine.CyclicLogic();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="36" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>